### ISSUE TITLE
bug with combat_mastery SQ

### ISSUE THREAD

**Issue by jhhudso** [DarkCastleMUD/DarkCastle#139]
Warrior on port 6666 got stuck in middle of SQ after a reboot or crash. Their varstat output was:
ready4diploma                  --  true
combat_mastery_sting           --  true
combat_mastery_talon           --  loaded
combat_mastery_whip            --  true
combat_mastery_blade           --  loaded
combat_mastery_bludgeon        --  true
combat_mastery_phaser          --  loaded
combat_mastery_crush           --  true
wants2fight                    --  true
combat_mastery_flail           --  loaded
victim                         --  null
combat_mastery_bludged         --  done
combat_mastery_stung           --  done
combat_mastery_crushed         --  done
combat_mastery_whipped         --  done
informed                       --  true
worthy                         --  maybe

**Comment by TehDreadPirateRoberts** [comment]
Part of the reason he got stuck was because the crash reset some things and it must have also cleared the diploma from the mobs inventory....
@jhhudso we could solve part of the problem by using [save] on the tempvars... let me know if you want me to write that into the mprog or if we just figure that this is kinda a 1 off and we leave it.
MPSETTEMP <victim> <variable name> <data> [save]
