### ISSUE TITLE
Targeting items in inventory and on the ground

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#147]
If you attempt to target something that is in your inventory when something with the same keyword is also on the ground, you are unable to target either of them. Sometimes...
Eg. You have a backpack in your inventory and 1 is on the ground
- If you attempt to put something into 'backpack' it will put the item into the backpack in your inventory
- If you attempt to remove something from 'backpack' it says it does not contain the item
- If you attempt to remove the item with 2.backpack it says you do not see or have 2.backpack
- If you identify backpack it will identify the one in your inventory
- If you identify 2.backpack it says you could not find 2.backpack in your inventory or in this room

Please let me know if any further explanation is required.

**Comment by jhhudso** [comment]
After talking with Westley and players, I'm going to change the targeting as these examples show:

Examples:
get fish backpack     
get fish from backpack
Description:
Gets fish from backpack in inventory unless inventory has no backpack then it checks if a backpack is worn as equipment and gives an error because you can't remove an item from a worn container. If a backpack is not in inventory or worn then it checks the room for a backpack and gets the fish from backpack in room.

Examples:
get fish from backpack in inventory
get fish from backpack inventory
get fish backpack inventory
get fish backpack inv
get fish backpack i
Description
Gets fish from backpack in inventory.

Examples:
get fish from backpack in room
get fish from backpack room
get fish backpack room
get fish backpack ro
get fish backpack r
Description
Gets fish from backpack in room.

Examples:
look earring in equipment
look earring equipment
look earring eq
look earring e
Description
Looks at currently equipped earring.

Examples:
look earring in equipment
look earring equipment
look earring eq
look earring e
Description
Looks at currently equipped earring.

Examples:
look earring
Description
Checks inventory first for earring. If no earring if found then it checks equipped items for an earring. If no equipped earring is found then it checks the room.

**Comment by TehDreadPirateRoberts** [comment]
This was fixed
