### ISSUE TITLE
How do you set clan messageboard topics?

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#166]
Clan boards don't necessarily reflect the correct clan ownership:

Ex:
Uln'hyrr clan board shows "Clan TimeWarp" board when you look at it.
MOOR board shows "Clan Arcana"
Clan Ataxia's board topic is "Inane messages only"

Is there a way to set these that I'm unaware of?

**Comment by jhhudso** [comment]
As long as no on erases or looks at the board, I can make changes to the files, reboot and the correct titles will show up. But really the problem is more complicated than that. Whomever setup the clans on port 6969 and the latest incarnation of board code (kkoons I think), the clan numbers, board names and the code do not match. Clearly someone knew this because they put the correct (Timewarp) board objects in the correct rooms (uln'hyrr clan hall) because uln'hyrr on port 6969 is using the clan number that is hardcoded for timewarp in board.cpp. Strangely the boards only save when you erase or look at them, not when you write a message which explains why a couple times people said board messages disappeared. You have to look at the board to make it save. I'll fix this too.

I will fix all the board/clan issues entirely eventually but just titles for now, the next reboot or two.

**Comment by TehDreadPirateRoberts** [comment]
"write Topic"
Topic needs to be capitalized like that when doing it. I have fixed all of the current clan boards.
