### ISSUE TITLE
Druid brewing:  Invalid recipe does not consume ingredients

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#169]
If you try and brew a potion with ingredients that do not add up to an active formula, you receive the message "As you finish, nothing special seems to happen." but the ingredients are not consumed.

IMO they should be.

**Comment by TehDreadPirateRoberts** [comment]
It works like this for both scribe and brew. The only reason I wouldn't want to do this is because ingredients (more so for scribe than brew) are difficult to get and if the items are consumed for the failed ones on a list you creating that is potentially 270 permutations.. well that would be super shit heh. 
If anyone still thinks otherwise, please open this again and let's discuss!
