### ISSUE TITLE
Add a "fade" message for insane chant

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#178]
Currently none exists.  Also we may want to look at the duration of that effect.  It seems like it lasts an inordinate amount of time for something that cannot be cured.  Suggest 2-3 pulses tops.

**Comment by TehDreadPirateRoberts** [comment]
It has a wear off message when it wears off from the bards song. But like other affects that are "bestowed" upon you it does not give a message when the timer on the affect runs out (like removing an item that gives you DI doesn't indicate you don't have DI anymore).
Also - the duration is due to the psionic class using MPBESTOW to give it to you for that long.

**Comment by TehDreadPirateRoberts** [comment]
Adjusted the duration (mob 152 prog 8).
The wear off message is because there are not any messages displayed for bestowed affects.
