### ISSUE TITLE
Strange issue with druid brewed potions - not sure if this is intended or not

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#53]
According to Twinkle, vaulted druid potions have not gone bad in the past, however - today he logged in and a ton of his potions have no effects anymore. He handed me four potions:

First one:  Obj# 6306
short desc::  A superior salty brownt(?) potion
long desc: A dark green herb has been dried and is ready for use
....has no spell effects

Second one:  Obj#  6324
short desc:  a superior salty brownt potion
long desc: a superior salty brownt potion lies here
has a level 36 spell of sanctuary

Third one: Obj# 6304
short desc: a plain salty bright yellow potion
long desc: This herb looks like it has been stepped on.
no spell effects

Fourth one: Obj# 6322
short desc: a plain salty bright yellow potion
long desc: a plain salty bright yellow potion lies here.
has level 34 spell of PFE

He apparently has tons of these potions and has no idea what's going on.  Any idea?  I don't know enough about brewing to tell whether this is intended behavior, but based upon the long descs of #1 and #3 it looks like something is screwed up perhaps?

**Comment by urizen-source** [comment]
Vaults use copySaveData in db.cpp copies things that should change, which does not include long desc and does not include item type, and the latter is why they break. V0 and V1 is copied for what spell and level it should have been, but since it's now of type OTHER instead of POTION it's useless.
I added long desc + item type to that code, should hopefully fix it. Not retroactively though, so broken items remain broken.
