### ISSUE TITLE
Mob Prog bug:  load_prog

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#55]
Helpfile states:

>Syntax:  load_prog <NUMBER>

>The argument is a percentage.

>NOTE:  **This prog will fire when the mob repops or is loaded.**  The
primary use of this prog type is to have a mobile 'spell-up' when
it loads.

Load progs do indeed fire when the mob repops as part of a zone-wide repop, but do not fire when a mob is spawned by an immortal or by a mob prog.  

(Submitted at Elder's request - also so I don't have to rework a bunch of mob progs)

**Comment by dmhenderson76** [comment]
While we're at it, can we add $i as an argument for MPADDLAG?  According to the helpfile, it currently does not work on mobs.  Makes it easier to space out mob combat actions more organically.

**Comment by urizen-source** [comment]
Fixed the load stuff. 
For now, not doing the MPADDLAG thing, that command adds the lag to sockets that checks for input from players, which is run alot more often than mobprogs cycle, which is the reason why mobs cannot be affected by this. Making mobprogs cycle as often is a bigger thing to change and verify that it works as intended, and due to limited time to spend coding I'll prioritize the other stuff there is to do for now. Feel free to open a separate issue if you really think it should be done and it can be looked at in the future. MPPAUSE works on a second-level at least, which seems pretty decent but I get that you might sometime want shorter pauses between mob commands but that'll have to wait.
