### ISSUE TITLE
Consecrate/Desecrate do not function as intended

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#6]
There are several things "wrong" with these skills.  I'm assuming some behaviors were not intended:

* The spell is not able to be cast by players in combat.  I believe (as discussed) that this was not the intended behavior.  This appears to have been an oversight but I cannot tell because I can't find the combat check for spells (found it for skills).  This is a combat spell that lasts 2-3 pulses tops and it fires on pulse, not on round.  Mobs cast it while in combat all the time but I'll get to that in a bit.  It is not feasible to initiate combat with consecrate/desecrate (since mob will win initiative negating most benefits from the spell).  In addition, it's probably not a good idea to start a pfight with a spell that leaves the caster sitting vulnerable for several seconds either while your opponent can simply walk out of the room.

*  These spells do not cause aggro tied to the caster.  This is... not right.  The object created by the spell should be tied to the player who created it, and damage dealt by it should be considered to be dealt by the player.  As of right now, the spell does not cause aggro when a mob is damaged and does not add to the mob's hate list.  Would be important to check if the mob is healed/damaged by the object pulse (healing should obviously not cause aggro) which brings me to...

*  This spell does not CANTQUIT flag players that damage other non-grouped players with it.

*  I have seen some very weird behavior tied to this spell.  If a mob casts consecrate and dies, other mobs that wander in while the spell is active aggro the player the previous mob was fighting even if that mob was not aggro to begin with.  Have only been able to replicate this once.

*  The ability to consecrate/desecrate multiple rooms is utterly pointless unless I'm missing something.  The spell duration is so short, that by the time you hit your max number of rooms, it has already faded.  Couple that with the reagent cost and large mana/mv expenditure, I just can't see a use for it.  Instead, might I suggest adding a "sticky"/snare effect to the spell hitting everyone in the room including the caster.  Players could still recall, but not flee/walk out of the room until the spell concludes.

*  Mobile casts of consecrate/desecrate deal no damage and do not heal anyone (including the mob).  Many mobs use these skills and they simply do not work when a mob casts.  Mobs should have the same rules as the player and should only use the spell in certain situations - EX: a paladin mob should case consecrate if fighting evil opponents, but should not use it if opponent is good or neutral (as it would heal them).

**Proposed changes:**
1) Make consecrate and desecrate combat castable.  This is the final spell/skill that antis and paladins receive.  It should be something useful.  In its current state, it is not.
2) Spell requirements are fine (mana and mv) but I think it should also move the caster's alignment towards zero randomly by 50-100 each cast making it less effective in repeated casts during long fights as the spell's effectiveness is dictated by the caster's alignment.
3) Take a look at the consecrate code and figure out why mobs can cast it, but not receive any of the benefits from it.  I'm stumped on this one.
4) If the spell damages a player not grouped with the caster, it should CQ flag them.   Players grouped with the caster should not generate CQs on damage - but should still take damage/be healed as appropriate (this is a little different than other AoE spells in that it can directly benefit/heal the group - so grouped damage immunity would be inappropriate here).
5) Mobs damaged by the spell should immediately attack the caster if not in combat and add caster to their hate list
6) Remove the ability/check to see how many consecrations the caster has active and replace with a snare effect that hits all combatants in the room until the spell concludes (including caster).

**Comment by urizen-source** [comment]
Hey Mark :) 

I can fix some of this tonight.. 
Looked some basic over it now, and a few thoughts, but will look closer tonight.
1) pretty sure there's a crashbug with how it accesses the creator during pulses, will look closer.
2) I agree, it looks like mobs should be affected, but the message is only to the person affected, nothing to room. Are we sure they are not affected? Should a message to room be added? 
3) So the duration seems low yeah, 1+skill/50, so max 2 regen pulses = max 30 secs, likely less as you're going to cast it sometime during the first pulse.. What would be reasonable, do we think? 

I can make it so that the damage is from the original caster instead of just deducting HPS as it is now, which fixes hatelist, CQ and such. Means all other damage stuff will also go into affect, such as sanc and such, or maybe this is meant to bypass everything like that?

**Comment by dmhenderson76** [comment]
> I agree, it looks like mobs should be affected, but the message is only to the person affected, nothing to room. Are we sure they are not affected? Should a message to room be added?

* I can't be 100% certain on this- easiest way to do it would be to have someone possess a mob that has the proc to use it.  I *can* say for certain that the mob's spell does not appear to do any damage to players.
* A room damage message would be extremely spammy (a room pulse message already occurs) but I think a message to caster and victim(s) would be helpful:
            -You take <x> damage from <casster>'s consecration / You are healed for <x> by <caster's> consecration
            - (caster perspective) Your consecration/desecration heals <target> for <x> or makes <target> suffer for <x>

> So the duration seems low yeah, 1+skill/50, so max 2 regen pulses = max 30 secs, likely less as you're going to cast it sometime during the first pulse.. What would be reasonable, do we think?

Make it castable in combat.  Duration should be low but maybe increase by 1 pulse- it's a powerful tool.  If the player can recast the spell while in combat, it basically serves to supplement their healing/damage dealing and adds a new wrinkle to their combat pattern with each successive cast moving their alignment towards zero - (making it less effective).  I think deducting 50 align per-cast is fine.

Also this is Raha-Mark, not Elder-Mark

**Comment by urizen-source** [comment]
* Made it castable in combat.
* Added 1 regen pulse to duration.
* Added message to caster, should make it easier to figure out what's going on.
* Fixed some how it keeps track of who "owns" the consecration-item, right now it used "name" which works for PCs(unless they quit), but seems hit and miss for mobs. Changed it to point to the correct character object with a bunch of checks so that they still exist before using it.
* Wasn't as easy as that to use the existing damage code as we are not guaranteed the caster still exists, so I added cantquit checks to the existing code, with a groupcheck.
* Added align deduction. No checks on align since there are already checks that pals need to be good and antis evil.


There is an "issue" still. If a mob casts it, and dies, and then a player dies from the item, it will count as a pkill as when it does not find the caster it defaults to that.. Not sure if that's worth doing anything about, but that's how it is. 


Or the above has a pull request for it anyway, https://github.com/DarkCastleMUD/DarkCastle/pull/8 


Oh and figured out which Mark, but it's been so long that I had to look your name up in my mailbox to find an old Uln'hyrr chain :)

**Comment by dmhenderson76** [comment]
Love the new functionality.  Had some fun with it last night but:

- Snare effect instead of multiple room cast possible?

- NPC casts of consecrate desecrate still do not damage PCs (log follows)
     * NPC is Tharkes from Jundlehem (evil) casts desecrate.  Saved the combat spam but caught it at the end of the fight when I was just standing around at +890 align and it did no damage at all.


**8072**/1123/1004/890 Tank is:   Victim is:   l
A harem room
The head of Vykryn-lothra, the Tempter is lying here.
the corpse of a black-cloaked imperial guardsman is lying here. [Excellent]
the corpse of a black-cloaked imperial guardsman is lying here. [Excellent]
the corpse of Emperor Tharkes the Mad, Tyrant of Khromilldor is lying here. [Excellent]
Exits: north-closed up 
The glowing circle pulses gently. **<----should have damaged me here**

**8072**/1123/1004/890 Tank is:   Victim is:   
Dread Pirate Vassago newbies 'wb, lots of us back after that much time too'

8072/1123/1004/890 Tank is:   Victim is:   cru

8196/1171/1004/890 Tank is:   Victim is:   You put a star shaped axe in Sheldon's Mysterious Backpack.

8196/1171/1004/890 Tank is:   Victim is:   You get the Illusionary Spellsword from Sheldon's Mysterious Backpack.

8196/1171/1004/890 Tank is:   Victim is:   You wield the Illusionary Spellsword.

8196/1171/1004/890 Tank is:   Victim is:   You stop using Diocletian's Praetorian Scimitar.

8196/1171/1004/890 Tank is:   Victim is:   You put Diocletian's Praetorian Scimitar in Sheldon's Mysterious Backpack.

8196/1171/1004/890 Tank is:   Victim is:   The backpack does not contain the death.

8196/1171/1004/890 Tank is:   Victim is:   You wield Death's Black Axe.

**8196/**1171/1004/890 Tank is:   Victim is:   newbie
The glowing circle pulses gently **<----should have damaged me here.**

**8196**/1171/1004/890 Tank is:   Victim is:

**Comment by dmhenderson76** [comment]
Hi Urizen, how can I contact you?  I needed some help with mob prog editing and Elder suggested I speak with you if you'd be willing to give me a hand.

**Comment by dmhenderson76** [comment]
Still broken.  Mob-cast consecrate/desecrate do not hit players when they should.  Weirdly enough, these spells *will* hit other mobs if cast by anther mob for the duration of the spell.

**Comment by TehDreadPirateRoberts** [comment]
Old way of this working for mobs was a "fake" consecrate/desecrate from within their default class mprog.
Mobs can now cast it.
Default paladin and anti mprogs have been update.
