### ISSUE TITLE
Item type "totem" refuses to play by zonefile command rules

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#71]
Totems refuse to follow zonefile command limitations.  Setting the "2" argument in a load line for a totem does nothing.  Unless the item is set to "onboot", it will spawn every single time a zone repops.

This causes a couple problems:
1) Right now if a totem scraps or is junked, it's gone until next reboot.  If this were fixed, you could have it so totems would repop if no other exist in the world.

2) This poses a problem for the new area that clears/repops every cycle.  If the totems aren't found by the first players inside, they are lost forever.

Ex:
{271] Comment:  Load swirled marble figurine and give to shambling warrior if eligible
[272] Always  Equip obj [30056] (if< [  1]) on last mob on [18](Held).

You hear unmatched screams of terror as all mobs are summarily executed!
You have just caused the destruction of countless creatures in ths area!
//(god) Ozymandias just CLEARED zone #161! 

Z:161 R:30096 I:0> repop
Resetting this entire zone!
//(god) Ozymandias repopped zone #161. 
Jeff sighs, puts out his cigarette and attempts to find a comfortable napping position in the shade.

Z:161 R:30096 I:0> find o figurine
-#-- Short Description ------- Room Number

[ 1] A swirled marble figurine  30053 equipped by szrildorian shambling zombie warrior
[ 2] A swirled marble figurine  2333 in an altar to Vhaerun

**Comment by dmhenderson76** [comment]
Workaround for this:  Clear/repop now does NOT affect items lying on the ground.  This is still broken though.

**Comment by dmhenderson76** [comment]
Still valid but not high priority

**Comment by TehDreadPirateRoberts** [comment]
This is happening because case 'E' does not check arg2. So it actually isn't only happening with totems, it happens with all objects that are set to 'equip' in the zone file.
Case 'O', 'P', 'G' & 'M' however do all have checks for arg2.

So basically... it is meaningless for case 'E'...

The fix for this would likely be to redo E to no longer have a second arg but I personally don't feel it is worth it (Jared if you do, please reopen this). 

When I looked into gitblame for the change, it looks like the change to making arg2 no longer relevant was made 17 years ago or more...
