### ISSUE TITLE
Druid elemental aura issues:  Screw-up on height change, missing spells that should be included

### ISSUE THREAD

**Issue by dmhenderson76** [DarkCastleMUD/DarkCastle#79]
What the help file says druid elemental auras do:

>Furthermore, at the highest levels of skill, the elemental's aura will be so powerful as to provide
>the druid and his or her group with an "enhanced elemental aura" of the
>same type as the elemental.  These auras will provide some enhancement
>to the groups' offensive spells of the appropriate type.

Edit:  This isn't correct.  They DO modify spell damage, just not by very much but read on, there is an actual problem here.

ALSO - when an elemental wears an item that modifies height (mammoth skin for instance), the aura vanishes?  What the heck?

**Comment by TehDreadPirateRoberts** [comment]
So, it turns out that the height thing is how elementals verify if you get the aura or not. I don't know of another way yet to do this, but maybe there should be a different check for this.
(the height is set in conjure_elemental in magic.cpp, the aura check is in magic.cpp under elemental_score)
For the increased damage to spells.. there is a hardcoded list in magic.cpp under int elemental_damage_bonus. However, there are currently only 17 spells listed there, lots are missing.

The following spells need to be added (just below line 9390 in magic.cpp):
FIRE:
case SPELL_BURNING HANDS:
case SPELL_SOLAR_GATE:
EARTH:
case SPELL_EARTHQUAKE:
case SPELL_BEE_SWARM:
case SPELL_MAGIC_MISSILE:
ICE:
case SPELL_ICESTORM:

The amount of damage done from this should also be changed but needs further discussion.

**Comment by TehDreadPirateRoberts** [comment]
A workaround might be to use weight instead of height...

**Comment by dmhenderson76** [comment]
Disagree, because there are items that modify weight too.  The best way to do this in my mind is to have to separate vnums for summoned elementals:  One where caster skill is <81 and one for 81 or more.  The 81+ variant has the aura, the other does not.  That seems kinda like the 'correct' solution - tying it to a variable that can change just doesn't seem like a good idea because who knows what might happen in the future...  Besides, that's exactly how cleric/anti charmies are done.  Not sure why elementals were treated differently.

**Comment by dmhenderson76** [comment]
This is still valid - remains open

**Comment by TehDreadPirateRoberts** [comment]
Changed the way that elemental aura works so that is no longer removed when elemental height changes.
Add a little more damage bonus to spells when elemental aura is present.
