### ISSUE TITLE
Apparently ki disrupt doesn't work on lightning shield

### ISSUE THREAD

**Issue by TehDreadPirateRoberts** [DarkCastleMUD/DarkCastle#90]
https://github.com/DarkCastleMUD/DarkCastle/blob/8fd8304eec644ed760c9150a4fe0c0f095676d01/src/ki.cpp#L858-L863

According to local monks, ki disrupt doesn't work on lightning shield. I have no idea if this is why or if there is another reason, but for dispel magic (line 5437 in magic.cpp) - there is this line: 	      REMBIT(victim->affected_by, AFF_LIGHTNINGSHIELD);

Interestingly, not all of the ways that they are written on dispel magic exist in the same way for ki disrupt code. But I am just guessing here...

**Comment by bdunavant** [comment]
Dispel and ki-disrupt are not intended to be clones of each other, but similar spells with different idiosyncrasies (otherwise, we'd just have one call the function for the other).   In this case, ki-disrupt would remove the spell version, but not from innate non-spell version of lightning shield on many mobs, or gear.  e.g. ki disrupt can disrupt the magic, but not "natural" versions.   Granted, what we want to do now is up to the current writers, I'm just providing some context.

**Comment by dmhenderson76** [comment]
I'm with Pirahna here.  Dispel and disrupt were not meant to be clones of each other - disrupt is FAR more effective (percentage-wise) and should come with a drawback.  If anything, I'd argue it should not be able to dispel innate shields at all (not cast shields) - making it far more effective against classed mobs than mobs with built-in shields.

**Comment by TehDreadPirateRoberts** [comment]
Oh for sure, I see the differences as far as the missing spells. And that makes more sense in regards to innate vs non-innate. Interesting... need to get some others to pipe in on this.

**Comment by TehDreadPirateRoberts** [comment]
Works as supposed to apparently. 👍
